project:
  type: book
  output-dir: docs

book:
  title: "Basic IFR"
  author: "Rainer RQ Koelle"
  date: "24. January 2025"
  chapters:
    - index.qmd
    - intro.qmd
    - 010-air-law.qmd
    - 0x0-human-factors.qmd
    - 030-flight-planning-and-monitoring.qmd
    - 040-meteology.qmd
    - 0x0-instrumentation.qmd
    - 050-human-performance.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



